import type { RoadMap } from '../../src/world';
// Three directed lanes form a cycle; one declared intersection joins a -> b.
export function minimalMap(): RoadMap {
  const point = (id: string, x: number, z: number) => ({ id, positionM: { x, y: 0, z } });
  return {
    schemaVersion: 1,
    units: 'SI',
    mapId: 'minimal-road-v1',
    bounds: { minM: { x: -5, y: 0, z: -5 }, maxM: { x: 25, y: 0, z: 25 } },
    geometry: {
      nodes: [
        point('n-a', 0, 0),
        point('n-b', 9, 0),
        point('n-c', 11, 0),
        point('n-d', 20, 0),
        point('n-loop', 20, 20),
        point('j1', 8, -2),
        point('j2', 12, -2),
        point('j3', 12, 2),
        point('j4', 8, 2),
        point('s1', -1, -1),
        point('s2', 1, -1),
        point('s3', 1, 1),
        point('s4', -1, 1),
        point('line-a', 8.5, -1),
        point('line-b', 8.5, 1),
        point('walk-a', 19, 18),
        point('walk-b', 21, 18),
        point('walk-c', 21, 21),
        point('walk-d', 19, 21),
        point('wline-a', 19, 19),
        point('wline-b', 21, 19),
      ],
      paths: [
        { id: 'g-a', nodeIds: ['n-a', 'n-b'] },
        { id: 'g-b', nodeIds: ['n-c', 'n-d'] },
        { id: 'g-c', nodeIds: ['n-d', 'n-loop', 'n-a'] },
        { id: 'g-move', nodeIds: ['n-b', 'n-c'] },
        { id: 'g-stop', nodeIds: ['line-a', 'line-b'] },
        { id: 'g-cross-stop', nodeIds: ['wline-a', 'wline-b'] },
      ],
      areas: [
        { id: 'g-junction', vertexNodeIds: ['j1', 'j2', 'j3', 'j4'] },
        { id: 'g-service', vertexNodeIds: ['s1', 's2', 's3', 's4'] },
        { id: 'g-crosswalk', vertexNodeIds: ['walk-a', 'walk-b', 'walk-c', 'walk-d'] },
      ],
    },
    lanes: [
      {
        id: 'lane-a',
        geometryId: 'g-a',
        direction: 'FORWARD',
        widthM: 3.5,
        speedLimitMps: 13.4,
        access: ['TAXI', 'CIVIL'],
        neighbors: { left: null, right: null },
        successorIds: ['lane-b'],
        fromIntersectionId: null,
        toIntersectionId: 'junction',
      },
      {
        id: 'lane-b',
        geometryId: 'g-b',
        direction: 'FORWARD',
        widthM: 3.5,
        speedLimitMps: 13.4,
        access: ['TAXI', 'CIVIL'],
        neighbors: { left: null, right: null },
        successorIds: ['lane-c'],
        fromIntersectionId: 'junction',
        toIntersectionId: null,
      },
      {
        id: 'lane-c',
        geometryId: 'g-c',
        direction: 'FORWARD',
        widthM: 3.5,
        speedLimitMps: 13.4,
        access: ['TAXI', 'CIVIL'],
        neighbors: { left: null, right: null },
        successorIds: ['lane-a'],
        fromIntersectionId: null,
        toIntersectionId: null,
      },
    ],
    intersections: [
      {
        id: 'junction',
        geometryId: 'g-junction',
        incomingLaneIds: ['lane-a'],
        outgoingLaneIds: ['lane-b'],
        conflictZones: [{ id: 'conflict', geometryId: 'g-junction' }],
        movements: [
          {
            id: 'move',
            geometryId: 'g-move',
            fromLaneId: 'lane-a',
            toLaneId: 'lane-b',
            conflictZoneIds: ['conflict'],
          },
        ],
      },
    ],
    signals: [
      {
        id: 'signal',
        intersectionId: 'junction',
        phases: [
          { id: 'green', durationS: 15, movementStates: [{ movementId: 'move', state: 'GREEN' }] },
          { id: 'red', durationS: 3, movementStates: [{ movementId: 'move', state: 'RED' }] },
        ],
      },
    ],
    stopLines: [
      {
        id: 'signal-stop',
        geometryId: 'g-stop',
        laneId: 'lane-a',
        anchorNodeId: 'n-b',
        kind: 'SIGNAL',
        intersectionId: 'junction',
        signalId: 'signal',
      },
      {
        id: 'cross-stop',
        geometryId: 'g-cross-stop',
        laneId: 'lane-c',
        anchorNodeId: 'n-loop',
        kind: 'CROSSWALK',
        intersectionId: null,
        signalId: null,
      },
    ],
    crosswalks: [
      {
        id: 'crosswalk',
        geometryId: 'g-crosswalk',
        laneIds: ['lane-c'],
        stopLineIds: ['cross-stop'],
      },
    ],
    serviceZones: [
      {
        id: 'service',
        geometryId: 'g-service',
        laneId: 'lane-a',
        anchorNodeId: 'n-a',
        access: ['TAXI', 'CIVIL'],
        kind: 'BOTH',
      },
    ],
    recoveryPoints: [{ id: 'recovery', nodeId: 'n-d', laneId: 'lane-b', headingRad: 0 }],
  };
}
