import {lifecycleCycles} from './lifecycle';import {check} from './proof';import {errorEvidence} from './diagnostics';import type {RenderingBackend} from '../../../src/rendering/babylon';
const button=document.getElementById('preflight') as HTMLButtonElement,full=document.getElementById('run') as HTMLButtonElement,status=document.getElementById('status')!;
button.addEventListener('click',async()=>{check(!button.disabled&&!full.disabled,'Capture already active');button.disabled=true;full.disabled=true;const requestedBackend=(document.getElementById('backend') as HTMLSelectElement).value as 'AUTO'|'WEBGL2';let failure:unknown=null,captureId:string|null=null,cycles=0,worldsCreated=0,listeners=0,sourceHash:string|null=null,artifactHash:string|null=null,renderer:string|null=null,invalid:string|null=null;const startedAt=new Date().toISOString();const blur=()=>{invalid??='WINDOW_BLUR';},visibility=()=>{if(document.hidden)invalid??='HIDDEN';};window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);listeners=2;
 const post=async(path:string,value:unknown)=>{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});const text=await response.text();check(response.ok,'Preflight transport '+response.status+':'+text);return JSON.parse(text);};
 try{const ready=await fetch('/capture-ready');check(ready.ok,await ready.text());const start=await post('/preflight-start',{requestedBackend,startedAt});captureId=start.captureId;sourceHash=start.sourceHash;artifactHash=start.artifactHash;renderer=start.renderer;status.textContent='RUNNING lifecycle preflight only20cycles '+requestedBackend;
 const surface=(b:RenderingBackend)=>{check(invalid===null&&document.hasFocus()&&!document.hidden,'Preflight foreground/context invalidated:'+invalid);const engine=b.scene.getEngine();check(devicePixelRatio===1&&b.canvas.clientWidth===1920&&b.canvas.clientHeight===1080&&engine.getRenderWidth()===1920&&engine.getRenderHeight()===1080,'Preflight actual CSS/internal/DPR');};
 await lifecycleCycles(document.getElementById('canvas') as HTMLCanvasElement,requestedBackend,surface,()=>{worldsCreated++;},async record=>{const ack=await post('/preflight-cycle',{captureId,requestedBackend,ordinal:cycles,record});check(ack.accepted===true&&ack.captureId===captureId&&ack.ordinal===cycles,'Exact cycle ACK');cycles++;});
 }catch(error){failure=error;}finally{window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);listeners=0;}
 try{if(captureId)await post('/preflight-finish',{captureId,requestedBackend,sourceHash,artifactHash,renderer,status:failure?'FAILED':'PASS',cycles,worldsCreated,listeners,foreground:document.hasFocus()&&!document.hidden,invalidated:invalid,startedAt,createdAt:new Date().toISOString(),causes:failure?[errorEvidence(failure)]:[],scope:'PREFLIGHT_ONLY_NOT_FULL_ACCEPTANCE'});}catch(error){failure=new AggregateError([...(failure?[failure]:[]),error],'Preflight original/terminal transport causes');}
 status.textContent=failure?'FAILED preflight '+String(failure):'PREFLIGHT cycles20 exported; independent proof required; FULL still pending';button.disabled=false;full.disabled=false;});
